FROM python:3.13-slim

WORKDIR /app

# Copy requirements and install dependencies
COPY services/inference_service/requirements.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy application code
COPY services/inference_service/ /app/
COPY services/orm /app/orm

# Run the inference service
CMD ["python","main.py"]
