version: '3.8'

services:
  kafka1:
    image: confluentinc/cp-kafka:7.8.6
    container_name: kafka1
    environment:
      KAFKA_KRAFT_MODE: 'true'
      CLUSTER_ID: 'kafka'
      KAFKA_NODE_ID: '1'
    

      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka1:9093,2@kafka2:9093,3@kafka3:9093"   #controllers communicate on port 9093host hwa kafka w
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: '3'

      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT"

      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      KAFKA_LOG_DIRS: /var/lib/kafka/kraft-combined-logs
    volumes:
      - kafka1_kraft:/var/lib/kafka/data
    networks:
      - SentinelNetwork
    healthcheck:
      test: ["CMD-SHELL", "kafka-broker-api-versions --bootstrap-server localhost:9092 >/dev/null 2>&1"]
      interval: 10s
      timeout: 5s
      retries: 12
  kafka2:
    image: confluentinc/cp-kafka:7.8.6
    container_name: kafka2
    environment:
      KAFKA_KRAFT_MODE: 'true'
      CLUSTER_ID: 'kafka'
      KAFKA_NODE_ID: '2'

      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka1:9093,2@kafka2:9093,3@kafka3:9093"  
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: '3'

      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT"
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      KAFKA_LOG_DIRS: /var/lib/kafka/kraft-combined-logs
    volumes:
      - kafka2_kraft:/var/lib/kafka/data
    networks:
      - SentinelNetwork
    healthcheck:
      test: ["CMD-SHELL", "kafka-broker-api-versions --bootstrap-server localhost:9092 >/dev/null 2>&1"]
      interval: 10s
      timeout: 5s
      retries: 12
  kafka3:
    image: confluentinc/cp-kafka:7.8.6
    container_name: kafka3
    environment:
      KAFKA_KRAFT_MODE: 'true'
      CLUSTER_ID: 'kafka'
      KAFKA_NODE_ID: '3'

      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka1:9093,2@kafka2:9093,3@kafka3:9093"  
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: '3'

      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka3:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT"

      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      KAFKA_LOG_DIRS: /var/lib/kafka/kraft-combined-logs
    volumes:
      - kafka3_kraft:/var/lib/kafka/data
    networks:
      - SentinelNetwork
    healthcheck:
      test: ["CMD-SHELL", "kafka-broker-api-versions --bootstrap-server localhost:9092 >/dev/null 2>&1"]
      interval: 10s
      timeout: 5s
      retries: 12
  kafka-init:
    image: confluentinc/cp-kafka:7.8.6
    container_name: kafka-init
    depends_on:
      kafka1:
        condition: service_healthy
      kafka2:
        condition: service_healthy
      kafka3:
        condition: service_healthy
    networks:
      - SentinelNetwork
    command:
      - /bin/bash
      - -lc
      - |
          echo "Creating topics..."
          kafka-topics --bootstrap-server kafka1:9092,kafka2:9092,kafka3:9092 --create --if-not-exists --topic raw_events --partitions 3 --replication-factor 3
          kafka-topics --bootstrap-server kafka1:9092,kafka2:9092,kafka3:9092 --create --if-not-exists --topic features --partitions 3 --replication-factor 3
          kafka-topics --bootstrap-server kafka1:9092,kafka2:9092,kafka3:9092 --create --if-not-exists --topic predictions --partitions 3 --replication-factor 3
          echo "Topics now:"
          kafka-topics --bootstrap-server kafka1:9092,kafka2:9092,kafka3:9092 --list
    restart: "no"
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_DB: sentinel
      POSTGRES_USER: sentinel_user
      POSTGRES_PASSWORD: sentinel_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - SentinelNetwork
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sentinel_user -d sentinel"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped
  process_data:
    build:
      context: ../services/data_process_service
    container_name: process-data
    depends_on:
      kafka-init:
        condition: service_completed_successfully
    environment:
      BOOTSTRAP_SERVERS: "kafka1:9092,kafka2:9092,kafka3:9092"
      IN_TOPIC: "raw_events"
      OUT_TOPIC: "features"
    networks:
      - SentinelNetwork
    restart: unless-stopped
  event_generator:
    build:
      context: ..
      dockerfile: services/event_generator_service/Dockerfile
    container_name: event_generator
    depends_on:
      kafka-init:
        condition: service_completed_successfully
      postgres:
        condition: service_healthy
    environment:
      KAFKA_BOOTSTRAP_SERVERS: "kafka1:9092,kafka2:9092,kafka3:9092"
      KAFKA_FEATURES_TOPIC: "raw_events"
      GENERATION_INTERVAL: "1.0"
      DATASET_PATH: "/app/data/transactions.csv"
      DB_HOST: "postgres"
      DB_PORT: "5432"
      DB_NAME: "sentinel"
      DB_USER: "sentinel_user"
      DB_PASSWORD: "sentinel_pass"
    networks:
      - SentinelNetwork
    restart: unless-stopped
  inference_service:
    build:
      context: ..
      dockerfile: services/inference_service/dockerfile
    container_name: inference_service
    depends_on:
      kafka-init:
        condition: service_completed_successfully
      postgres:
        condition: service_healthy
    environment:
      KAFKA_BOOTSTRAP_SERVERS: "kafka1:9092,kafka2:9092,kafka3:9092"
      KAFKA_GROUP_ID: "inference-service"
      KAFKA_FEATURES_TOPIC: "features"
      KAFKA_PREDICTIONS_TOPIC: "predictions"
      KAFKA_AUTO_OFFSET_RESET: "earliest"
      DB_HOST: "postgres"
      DB_PORT: "5432"
      DB_NAME: "sentinel"
      DB_USER: "sentinel_user"
      DB_PASSWORD: "sentinel_pass"
      MLFLOW_TRACKING_URI: "http://mlflow-server:5000"
    networks:
      - SentinelNetwork
      - sentinel-mlflow-network
    restart: unless-stopped
volumes:
  kafka1_kraft:
  kafka2_kraft:
  kafka3_kraft:
  postgres_data:
  event_generator_offset:
networks:
  SentinelNetwork:
    driver: bridge
  sentinel-mlflow-network:
    driver: bridge